### PR TITLE
Add aws s3 bucket as storage backend option

### PR DESCRIPTION
**Pull request by ffilippopoulos**
This PR adds aws s3 as backend storage.

The goal of this one was to have a storage backend that is remote to the deployment and could keep ignition data encrypted and communicate it downstream securely.
That allowed us to scale up our k8s matchbox deployments and make matchobox highly available:

```
NAME                           READY   STATUS    RESTARTS   AGE
matchbox-s3-85ff8776cc-4gwm7   1/1     Running   0          37m
matchbox-s3-85ff8776cc-jcsqq   1/1     Running   0          37m
matchbox-s3-85ff8776cc-wcdgs   1/1     Running   0          40m
```

Also it will allow us to move matchbox as close to the boxes that rely on it to serve ignition over http but still fetching securely remote config and implement failovers in case
matchbox deployments are experiencing issues. 

The PR:
- adds a very simple (`s3.go`) client that serves reading, listing, writing and deleting objects
- implements and s3BucketStore (Store) based on the above client
- adds a fake/mock client and tests for the aboce 2.
- adds the newly needed dependencies under vendor and updates `go.mod`

We currently have a working deployment of this and looking forward to hearing feedback :))

### CODE REVIEW

**Comment by ffilippopoulos** [comment]
fixed errors reported by lint :))

**Comment by dprint8** [comment]
+1

**Comment by dghubble** [comment]
I've been pondering this one. I did originally design Matchbox storage (with builtin filestore) to allow implementations to satisfy the interface and this is a nice usage of that for S3. I'm super glad it has worked for you and continues to. 

But today, there are [dozens of persistent volume](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes) options available on different platforms for Matchbox persistence and with different read/write modes for HA (e.g. AWS has EBS or EFS). Time has only made those storage abstractions more compelling. And Matchbox filestore just wants a directory at the end of the day.

I did once plan to go implement different backend plugins too. But its getting tough to argue applications (like Matchbox) should implement and maintain support for each storage vendor. After S3, we write Google Cloud Storage support? Azure Cloud Files? Probably not. Using a persistent volume is easier in the long run. It supports tons of backends. It lets users switch between them flexibly (EBS today, GPD tmrw?). Kubernetes massive base puts eyeballs on volume implementations. Vendors invest in their volume implementations. And it requires no Matchbox code changes or new dependencies. And apps don't implement storage details.

**Comment by ffilippopoulos** [comment]
@dghubble that is fair, I will close this PR and figure out what are the alternatives for us since this https://github.com/kubernetes/kubernetes/issues/13136 is preventing a read write many volume for our use case/deployment.
Thank you very much for looking at this and for your feedback!

**Pull request closed without merging**
